/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as ArticlesRouteImport } from './routes/articles'
import { Route as CareTeamRouteImport } from './routes/care-team'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as GiveRouteImport } from './routes/give'
import { Route as GroupsRouteImport } from './routes/groups'
import { Route as InsuranceRouteImport } from './routes/insurance'
import { Route as LocationRouteImport } from './routes/location'
import { Route as NewPatientsRouteImport } from './routes/new-patients'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VisitRouteImport } from './routes/visit'
import { Route as VolunteerRouteImport } from './routes/volunteer'
import { Route as ArticlesSlugRouteImport } from './routes/articles_.$slug'
import { Route as ServicesSlugRouteImport } from './routes/services_.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesRoute = ArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const CareTeamRoute = CareTeamRouteImport.update({
  id: '/care-team',
  path: '/care-team',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const GiveRoute = GiveRouteImport.update({
  id: '/give',
  path: '/give',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsRoute = GroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const InsuranceRoute = InsuranceRouteImport.update({
  id: '/insurance',
  path: '/insurance',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationRoute = LocationRouteImport.update({
  id: '/location',
  path: '/location',
  getParentRoute: () => rootRouteImport,
} as any)
const NewPatientsRoute = NewPatientsRouteImport.update({
  id: '/new-patients',
  path: '/new-patients',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VisitRoute = VisitRouteImport.update({
  id: '/visit',
  path: '/visit',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteerRoute = VolunteerRouteImport.update({
  id: '/volunteer',
  path: '/volunteer',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/articles_/$slug',
  path: '/articles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services_/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/appointments': typeof AppointmentsRoute
  '/articles': typeof ArticlesRoute
  '/care-team': typeof CareTeamRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/give': typeof GiveRoute
  '/groups': typeof GroupsRoute
  '/insurance': typeof InsuranceRoute
  '/location': typeof LocationRoute
  '/new-patients': typeof NewPatientsRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRoute
  '/stories': typeof StoriesRoute
  '/terms': typeof TermsRoute
  '/visit': typeof VisitRoute
  '/volunteer': typeof VolunteerRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/appointments': typeof AppointmentsRoute
  '/articles': typeof ArticlesRoute
  '/care-team': typeof CareTeamRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/give': typeof GiveRoute
  '/groups': typeof GroupsRoute
  '/insurance': typeof InsuranceRoute
  '/location': typeof LocationRoute
  '/new-patients': typeof NewPatientsRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRoute
  '/stories': typeof StoriesRoute
  '/terms': typeof TermsRoute
  '/visit': typeof VisitRoute
  '/volunteer': typeof VolunteerRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/appointments': typeof AppointmentsRoute
  '/articles': typeof ArticlesRoute
  '/care-team': typeof CareTeamRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/give': typeof GiveRoute
  '/groups': typeof GroupsRoute
  '/insurance': typeof InsuranceRoute
  '/location': typeof LocationRoute
  '/new-patients': typeof NewPatientsRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRoute
  '/stories': typeof StoriesRoute
  '/terms': typeof TermsRoute
  '/visit': typeof VisitRoute
  '/volunteer': typeof VolunteerRoute
  '/articles_/$slug': typeof ArticlesSlugRoute
  '/services_/$slug': typeof ServicesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/appointments'
    | '/articles'
    | '/care-team'
    | '/contact'
    | '/donate'
    | '/give'
    | '/groups'
    | '/insurance'
    | '/location'
    | '/new-patients'
    | '/privacy'
    | '/resources'
    | '/services'
    | '/stories'
    | '/terms'
    | '/visit'
    | '/volunteer'
    | '/articles/$slug'
    | '/services/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/appointments'
    | '/articles'
    | '/care-team'
    | '/contact'
    | '/donate'
    | '/give'
    | '/groups'
    | '/insurance'
    | '/location'
    | '/new-patients'
    | '/privacy'
    | '/resources'
    | '/services'
    | '/stories'
    | '/terms'
    | '/visit'
    | '/volunteer'
    | '/articles/$slug'
    | '/services/$slug'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/about'
    | '/appointments'
    | '/articles'
    | '/care-team'
    | '/contact'
    | '/donate'
    | '/give'
    | '/groups'
    | '/insurance'
    | '/location'
    | '/new-patients'
    | '/privacy'
    | '/resources'
    | '/services'
    | '/stories'
    | '/terms'
    | '/visit'
    | '/volunteer'
    | '/articles_/$slug'
    | '/services_/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  AppointmentsRoute: typeof AppointmentsRoute
  ArticlesRoute: typeof ArticlesRoute
  CareTeamRoute: typeof CareTeamRoute
  ContactRoute: typeof ContactRoute
  DonateRoute: typeof DonateRoute
  GiveRoute: typeof GiveRoute
  GroupsRoute: typeof GroupsRoute
  InsuranceRoute: typeof InsuranceRoute
  LocationRoute: typeof LocationRoute
  NewPatientsRoute: typeof NewPatientsRoute
  PrivacyRoute: typeof PrivacyRoute
  ResourcesRoute: typeof ResourcesRoute
  ServicesRoute: typeof ServicesRoute
  StoriesRoute: typeof StoriesRoute
  TermsRoute: typeof TermsRoute
  VisitRoute: typeof VisitRoute
  VolunteerRoute: typeof VolunteerRoute
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles': {
      id: '/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/care-team': {
      id: '/care-team'
      path: '/care-team'
      fullPath: '/care-team'
      preLoaderRoute: typeof CareTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/give': {
      id: '/give'
      path: '/give'
      fullPath: '/give'
      preLoaderRoute: typeof GiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups': {
      id: '/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insurance': {
      id: '/insurance'
      path: '/insurance'
      fullPath: '/insurance'
      preLoaderRoute: typeof InsuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/location': {
      id: '/location'
      path: '/location'
      fullPath: '/location'
      preLoaderRoute: typeof LocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-patients': {
      id: '/new-patients'
      path: '/new-patients'
      fullPath: '/new-patients'
      preLoaderRoute: typeof NewPatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visit': {
      id: '/visit'
      path: '/visit'
      fullPath: '/visit'
      preLoaderRoute: typeof VisitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteer': {
      id: '/volunteer'
      path: '/volunteer'
      fullPath: '/volunteer'
      preLoaderRoute: typeof VolunteerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles_/$slug': {
      id: '/articles_/$slug'
      path: '/articles/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services_/$slug': {
      id: '/services_/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  AppointmentsRoute: AppointmentsRoute,
  ArticlesRoute: ArticlesRoute,
  CareTeamRoute: CareTeamRoute,
  ContactRoute: ContactRoute,
  DonateRoute: DonateRoute,
  GiveRoute: GiveRoute,
  GroupsRoute: GroupsRoute,
  InsuranceRoute: InsuranceRoute,
  LocationRoute: LocationRoute,
  NewPatientsRoute: NewPatientsRoute,
  PrivacyRoute: PrivacyRoute,
  ResourcesRoute: ResourcesRoute,
  ServicesRoute: ServicesRoute,
  StoriesRoute: StoriesRoute,
  TermsRoute: TermsRoute,
  VisitRoute: VisitRoute,
  VolunteerRoute: VolunteerRoute,
  ArticlesSlugRoute: ArticlesSlugRoute,
  ServicesSlugRoute: ServicesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
